# install antidote if not exist
[[ -r ~/.antidote/antidote.zsh ]] ||
    git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
# load plugin 
source ~/.antidote/antidote.zsh
antidote load ~/.zsh_plugins.txt

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
(( ! ${+functions[p10k]} )) || p10k finalize

# PATH 
case `uname` in
  Darwin)
    export PATH=/opt/homebrew/bin:$PATH
  ;; 
  Linux)
    export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
    export PATH=$HOME/.local/bin:$PATH
  ;;
esac
export PATH=$HOME/.pub-cache/bin:$PATH

if [[ "$OSTYPE" == "darwin"* ]]; then
  export LC_ALL=en_US.UTF-8
fi

# Alias
alias gs="git status"

# fzf (fd)
if command -v fd &> /dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
elif command -v fdfind &> /dev/null; then
  export FZF_DEFAULT_COMMAND='fdfind --type f --strip-cwd-prefix'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# zoxide
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi

