# install antidote if not exist
[[ -r ~/.antidote/antidote.zsh ]] ||
    git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
# load plugin 
source ~/.antidote/antidote.zsh
antidote load ~/.zsh_plugins.txt

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
(( ! ${+functions[p10k]} )) || p10k finalize

# PATH 
case `uname` in
  Darwin)
    export PATH=/opt/homebrew/bin:$PATH
  ;; 
  Linux)
    export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
    export PATH=$HOME/.local/bin:$PATH
  ;;
esac
export PATH=$HOME/.pub-cache/bin:$PATH

# If Vim has error message 'Warning: Failed to set locale category LC_NUMERIC to en_TW.'. Uncomment it.
# export LC_ALL=en_US.UTF-8

# Alias
alias gs="git status"

# zoxide
eval "$(zoxide init zsh)"
